QUESTION 1


In [2]:
!pip install numpy


In [3]:
import numpy as np

In [4]:
print(np.__version__)

1.25.2


QUESTION 2

In [5]:
#define the housing price related feature for location
list_row1 = [-121.87,37.23,19,7357,963,30,18,981,6.9473]
list_row2 = [-121.12,39.03,17,838,161,38,8,142,3.6563]

In [6]:
#create two numpy arrays from row1 and row2
np_row1 = np.array(list_row1)
np_row2 = np.array(list_row2)

In [7]:
#check variables' data type
print(type(np_row1),'vs',type(list_row1))

<class 'numpy.ndarray'> vs <class 'list'>


In [8]:
#check 1D Numpy array' dimension
print("np_row1.shape", np_row1.shape)

np_row1.shape (9,)


a. Indexing in 1 dimension array (rank 1 -tensor)

In [9]:
#Indexing in 1 dimension numpy vector(rank 1 -tensor)
np_row1 = np.array([-121.87,37.23,19,7357,963,3018,981,6.9473])
print("np_row1: ",np_row1)

np_row1:  [-1.2187e+02  3.7230e+01  1.9000e+01  7.3570e+03  9.6300e+02  3.0180e+03
  9.8100e+02  6.9473e+00]


In [10]:
#Each element in the 1d array can be accessed by passing the positional index of the element.
print("np_row1[0]: ", np_row1[0])
print("np_row1[1]: ", np_row1[1])

np_row1[0]:  -121.87
np_row1[1]:  37.23


QUESTION 3

In [11]:
# Created 2D  Numpy Array based on nested list
np_rows = np.array([
    [-121.87,37.23,19,7357,963,3018,981,6.9473],
     [-121.12, 39.03, 17, 838, 161, 388, 142, 3.6563]
    ])
print("np_rows: ",np_rows)
print("np_rows.shape: ", np_rows.shape)


np_rows:  [[-1.2187e+02  3.7230e+01  1.9000e+01  7.3570e+03  9.6300e+02  3.0180e+03
   9.8100e+02  6.9473e+00]
 [-1.2112e+02  3.9030e+01  1.7000e+01  8.3800e+02  1.6100e+02  3.8800e+02
   1.4200e+02  3.6563e+00]]
np_rows.shape:  (2, 8)


In [12]:
#Indexing in 2 dimensions (rank 2 - tensor)
# We can retrieve an element of the 2D Numpy array using two indices i and j - i selects the row, and j selects the column:
# we can pass i-th row and j-th column in either one bracket or separate brackets ([])
print("np_rows[1,2]: ", np_rows[1,2]) # option 1
print("np_rows[1][2]:", np_rows[1][2]) # option2

np_rows[1,2]:  17.0
np_rows[1][2]: 17.0


QUESTION 4


In [14]:
A = np.array([
    [-121.87,-121.12,-119.31,-118.03,-120.97,-118.18,-117.7],
    [37.23,39.03,36.06,33.78,37.61,34.02,33.6],
    [19,17,20,25,16,37,16]
])
print("np_rows: ",A)
print("A.shape: ",A.shape)

print("np_rows[1,2]: ", np_rows[1,2])



np_rows:  [[-121.87 -121.12 -119.31 -118.03 -120.97 -118.18 -117.7 ]
 [  37.23   39.03   36.06   33.78   37.61   34.02   33.6 ]
 [  19.     17.     20.     25.     16.     37.     16.  ]]
A.shape:  (3, 7)
np_rows[1,2]:  17.0


QUESTION 5

In [15]:

A = np.array([
    [0, 50, 100, 150, 200],
    [20, 70, 120, 170, 220],
    [40, 90, 140, 190, 240],
    [60, 110, 160, 210, 255],
    [80, 130, 180, 230, 250]
])


print("np_rows: ",A)
print("A.shape: ",A.shape)


np_rows:  [[  0  50 100 150 200]
 [ 20  70 120 170 220]
 [ 40  90 140 190 240]
 [ 60 110 160 210 255]
 [ 80 130 180 230 250]]
A.shape:  (5, 5)


QUESTION 6

In [18]:
three_d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
])

print("np_rows: ",three_d)
print("three_d.shape: ",three_d.shape)



np_rows:  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
three_d.shape:  (3, 2, 3)


QUESTION 7

In [19]:
# Slicing in 1 dimension numpy vector (rank 1 -tensor)
# pick the second, third, and forth element from the array
np_location1 = np.array([-121.87, 37.23, 19, 7357, 963, 3018, 981, 6.9473])
print("np_location1[1:4]: ", np_location1[1:4])

np_location1[1:4]:  [  37.23   19.   7357.  ]


In [20]:
# define 2d array
np_locations = np.array([
  [-121.87, 37.23, 19, 7357, 963, 3018, 981, 6.9473],
  [-121.12, 39.03, 17, 838, 161, 388, 142, 3.6563],
  [-119.31, 36.06, 20, 2236, 434, 1405, 412, 1.8827]
])
print("np_locations: ", np_locations)

np_locations:  [[-1.2187e+02  3.7230e+01  1.9000e+01  7.3570e+03  9.6300e+02  3.0180e+03
   9.8100e+02  6.9473e+00]
 [-1.2112e+02  3.9030e+01  1.7000e+01  8.3800e+02  1.6100e+02  3.8800e+02
   1.4200e+02  3.6563e+00]
 [-1.1931e+02  3.6060e+01  2.0000e+01  2.2360e+03  4.3400e+02  1.4050e+03
   4.1200e+02  1.8827e+00]]


In [21]:
# select all rows except 1st row
# select 3rd and 4th column
print("np_locations[1:,2:4]: ", np_locations[1:,2:4])

np_locations[1:,2:4]:  [[  17.  838.]
 [  20. 2236.]]


QUESTION 8

In [24]:
## Perform matrix addition
A = np. random. rand (2,2)
print ("Matrix A: \n\n", A, "\n")
B = np. random. rand (2,2)
print ("Matrix B: \n\n", B, "\n")
C=A+B
print ("Matrix addition is: \n\n", C, "\n")

Matrix A: 

 [[0.53560342 0.72446235]
 [0.25360657 0.31219119]] 

Matrix B: 

 [[0.08935678 0.79335963]
 [0.87769843 0.35166555]] 

Matrix addition is: 

 [[0.6249602  1.51782197]
 [1.131305   0.66385674]] 



QUESTION 9

In [25]:
# adding the two arrays
np_location1 = np.array([-121.87, 37.23, 19, 7357, 963, 3018, 981, 6.9473])
np_location2 = np.array([-121.12, 39.03, 17, 838, 161, 388, 142, 3.6563])

np_location_sum = np_location1 + np_location2

print("np_location_sum: ",np_location_sum)

np_location_sum:  [-242.99     76.26     36.     8195.     1124.     3406.     1123.
   10.6036]


In [26]:
# get sum of values in array
print("np_location1.sum(): ", np_location1.sum())

np_location1.sum():  12260.3073


In [27]:
# get min of values in array
print("np_location1.min(): ", np_location1.min())

np_location1.min():  -121.87


In [29]:
# concatenate two 1D arrays
list_location1 = [-121.87, 37.23, 19, 7357, 963, 3018, 981, 6.9473]
list_location2 = [-121.12, 39.03, 17, 838, 161, 388, 142, 3.6563]

In [30]:
np_location_concat = np.concatenate([list_location1, list_location2])

print("np_location_concat: ", np_location_concat)

np_location_concat:  [-1.2187e+02  3.7230e+01  1.9000e+01  7.3570e+03  9.6300e+02  3.0180e+03
  9.8100e+02  6.9473e+00 -1.2112e+02  3.9030e+01  1.7000e+01  8.3800e+02
  1.6100e+02  3.8800e+02  1.4200e+02  3.6563e+00]


PROBLEM 1

In [39]:

latitude = np.array([37.23, 39.03, 36.06, 33.78, 37.61, 34.02, 33.6])
housing_median_age = np.array([19, 17, 20, 25, 16, 37, 16])
total_rooms = np.array([7357, 838, 2236, 3554, 1326, 2631, 2092])
population = np.array([3018, 388, 1405, 1600, 884, 3228, 877])
median_income = np.array([6.9473, 3.6563, 1.8827, 6.6453, 1.871, 2.15, 3.0461])

print("Latitude shape:", latitude.shape)
print("Housing median age shape:", housing_median_age.shape)
print("Total rooms shape:", total_rooms.shape)
print("Population shape:", population.shape)
print("Median income shape:", median_income.shape)


arrays = [latitude, housing_median_age, total_rooms, population, median_income]
names = ["Latitude", "Housing median age", "Total rooms", "Population", "Median income"]

names = ["Array1", "Array2", "Array3"]  # Example names
arrays = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])]  # Example arrays

print("\nStatistics for each array:")

name = names[0]
arr = arrays[0]
print(f"{name}:")
print(f"  Sum: {np.sum(arr):.2f}")
print(f"  Mean: {np.mean(arr):.2f}")
print(f"  Minimum: {np.min(arr):.2f}")
print(f"  Maximum: {np.max(arr):.2f}")

name = names[1]
arr = arrays[1]
print(f"{name}:")
print(f"  Sum: {np.sum(arr):.2f}")
print(f"  Mean: {np.mean(arr):.2f}")
print(f"  Minimum: {np.min(arr):.2f}")
print(f"  Maximum: {np.max(arr):.2f}")

name = names[2]
arr = arrays[2]
print(f"{name}:")
print(f"  Sum: {np.sum(arr):.2f}")
print(f"  Mean: {np.mean(arr):.2f}")
print(f"  Minimum: {np.min(arr):.2f}")
print(f"  Maximum: {np.max(arr):.2f}")


rows_2d = np.array([
    [-121.87, 37.23, 19, 7357, 963, 3018, 981, 6.9473],
    [-119.31, 36.06, 20, 2236, 434, 1405, 412, 1.8827],
    [-117.7, 33.6, 16, 2092, 489, 877, 392, 3.0461]
])

print("\nShape of 2-D array:")
print("2-D array shape:", rows_2d.shape)

Latitude shape: (7,)
Housing median age shape: (7,)
Total rooms shape: (7,)
Population shape: (7,)
Median income shape: (7,)

Statistics for each array:
Array1:
  Sum: 6.00
  Mean: 2.00
  Minimum: 1.00
  Maximum: 3.00
Array2:
  Sum: 15.00
  Mean: 5.00
  Minimum: 4.00
  Maximum: 6.00
Array3:
  Sum: 24.00
  Mean: 8.00
  Minimum: 7.00
  Maximum: 9.00

Shape of 2-D array:
2-D array shape: (3, 8)


PROBLEM  2


In [37]:
import tensorflow as tf

(mnist_images_training, _), (mnist_images_test, _) = tf.keras.datasets.mnist.load_data(path='mnist.npz')

11490434/11490434 [==============================] - 1s 0us/step


In [38]:
print("\nTask 1:")
print(f"mnist_images_training shape: {mnist_images_training.shape}")
print(f"mnist_images_training is a rank-{mnist_images_training.ndim} tensor")
print(f"mnist_images_test shape: {mnist_images_test.shape}")
print(f"mnist_images_test is a rank-{mnist_images_test.ndim} tensor")

print("\nTask 2:")
random_index = np.random.randint(0, mnist_images_training.shape[0])
random_image = mnist_images_training[random_index]
print(f"Random image shape: {random_image.shape}")


print("\nTask 3:")
subset_indices = np.random.choice(mnist_images_training.shape[0], 10, replace=False)
image_subset = mnist_images_training[subset_indices]
print(f"Image subset shape: {image_subset.shape}")

Task 1:
mnist_images_training shape: (60000, 28, 28)
mnist_images_training is a rank-3 tensor
mnist_images_test shape: (10000, 28, 28)
mnist_images_test is a rank-3 tensor

Task 2:
Random image shape: (28, 28)

Task 3:
Image subset shape: (10, 28, 28)
